
dna = 'GATTATCTCGAGAGTTGATAACTCGCGGTGCTACTGCAAGAGCGTCCACGCTAAAGGTCCGTACGAGTTGGATCCTACCTTTCAGCCCAAAAGTAGCTCGGATGACGCGGTTCACATCCGTTCGACTGCGAACGCATATGACGGAGCGGGATTGAAGTTTGGTCTACCGTTCGCGATCAGACAGGCGCAATTTCTTACTTCGCCCGCTGGGGTCGAGACATGAAGATGCGCAGTGACCGCTAGAATCCTAGAATCACATCGCTTAGCTTCCCAAAGAGGATGAAGCTAGCATTCCTCGCCTCCCTGCGAGCCCTTTCGTGGGATAATGCAACCGAGGCCCCGCTTGAAGCTTATCAGCTTACATCTTGAATCCGTTCGCACAGCTCCATGAGGAGTCCAGTATTCTGGATACGGAAAGTATGGTAATGTATAACTTCGGGTTATCCGTGTATCAAACTGCTCTCTGTACTGGATGCGCAGTAACAGAAGGTCTATCCTCACCAGGGGTACAGGCATCGTTGATTGATACCGTATTGTCCAAAATCAGATCTCGTTCTTACTCTGTCTAACAGTCAAGACGTGGAGAAGTCAGGGGGGCAACTGGTTCTGCCCGGTGCAAGAGTACCGGGCCTGAACCGGCTACAACGCGAAAGCTCTTCGGTCTTTCTGCAGTGAGCCGGCGAGTATATGGCAGCGTCATCCTATACCTGATTATGCCCGTCGGAGCTGTGTGGTCTGTAAAAACGAAAGCCGTGCCGGATTTTCCTGGCTGTTTTACACTTGTCATCCACTAAAAAGCTGGCTCATACGCGTTTTGGCCGTGGGAAGTAGCCCACTAGTACTTTGACCCCCCCCTCACACATGAAGGTCAGAATCGGACGAGTACGCAAACTACAAGTGCACTCGATTAGACCAAGAGTGATTCCACCCTAACAGTG'

strand = ''

for c in dna:
    if c == 'A':
        strand = 'T' + strand
    elif c == 'C':
        strand = 'G' + strand
    elif c == 'G':
        strand = 'C' + strand
    elif c == 'T':
        strand = 'A' + strand
print(strand)